MAPS_API_KEY=AIzaSyB_oHVAqtdIDvSUNyy1Icpyr5Lo6ryQg4M
GROQ_API_KEY=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
drivername = "postgresql+psycopg"
database = "uniandes_marketplace_db"
username = "uniandes_marketplace_db_user"
password = "vqvnOgf4sPLwNlOLNJ34kXsxrAgkjyIv"
host = "dpg-d7g2an1o3t8c73c0p8hg-a.or\"
API_BASE_URL = "https://uniandesmarketplacebackend.onrender.com/egon-postgres.render.com"
port = 5432